[build-system]
requires = ["setuptools >= 43", "setuptools_scm >= 6.2", "setuptools_rust"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
filterwarnings = [
    "error",
]
testpaths = ["tests"]
xfail_strict = true

[tool.setuptools_scm]
write_to = "src/cutadapt/_version.py"

[tool.mypy]
warn_unused_configs = true
